export const mobileFeatureList = [
  'Functional Android app',
  'Functional iOS app',
  'App design',
  'App submission',
  'App icon',
  'Splash screen',
  'Ad network integration',
  'Source code',
];

export const webFeatureList = [
  'Responsive website',
  'Custom UI/UX design',
  'SEO optimization',
  'CMS / content editing',
  'Contact & lead forms',
  'Admin dashboard',
  'Deployment & hosting setup',
  'Source code',
];

export const pricingCategories = {
  mobile: {
    id: 'mobile',
    label: 'Mobile apps',
    featureList: mobileFeatureList,
    plans: [
      {
        slug: 'starter',
        icon: 'mobile',
        name: 'Starter',
        tierLabel: 'Essential app builder',
        price: '$100+',
        desc: 'Mobile app build up to 3 screens, following your Figma design.',
        delivery: '5-day delivery',
        revisions: 'Unlimited revisions',
        included: [
          'Functional Android app',
          'Functional iOS app',
          'Source code',
        ],
      },
      {
        slug: 'growth',
        icon: 'react',
        name: 'Growth',
        tierLabel: 'Standard mobile app development',
        price: '$400+',
        desc: 'Mobile app development up to 10 screens, plus provided API integrations.',
        delivery: '14-day delivery',
        revisions: 'Unlimited revisions',
        featured: true,
        included: [
          'Functional Android app',
          'Functional iOS app',
          'App design',
          'App icon',
          'Splash screen',
          'Source code',
        ],
      },
      {
        slug: 'advanced',
        icon: 'rocket',
        name: 'Advanced',
        tierLabel: 'Pro custom app development',
        price: '$700+',
        desc: 'From Figma design to React Native development, deployment, and handoff.',
        delivery: '21-day delivery',
        revisions: 'Unlimited revisions',
        included: mobileFeatureList,
      },
    ],
  },
  web: {
    id: 'web',
    label: 'Web packages',
    featureList: webFeatureList,
    plans: [
      {
        slug: 'web-starter',
        icon: 'website',
        name: 'Starter',
        tierLabel: 'Essential landing page',
        price: '$100+',
        desc: 'High-converting landing page with responsive layout and clean handoff-ready code.',
        delivery: '5-day delivery',
        revisions: 'Unlimited revisions',
        included: [
          'Responsive website',
          'SEO optimization',
          'Contact & lead forms',
          'Source code',
        ],
      },
      {
        slug: 'web-growth',
        icon: 'nextjs',
        name: 'Growth',
        tierLabel: 'Standard website development',
        price: '$400+',
        desc: 'Multi-page business website up to 5 pages with modern UI and CMS-ready structure.',
        delivery: '10-day delivery',
        revisions: 'Unlimited revisions',
        featured: true,
        included: [
          'Responsive website',
          'Custom UI/UX design',
          'SEO optimization',
          'CMS / content editing',
          'Contact & lead forms',
          'Source code',
        ],
      },
      {
        slug: 'web-advanced',
        icon: 'webapp',
        name: 'Advanced',
        tierLabel: 'Pro web application',
        price: '$700+',
        desc: 'Full-stack web app with custom features, admin tools, deployment, and handoff.',
        delivery: '21-day delivery',
        revisions: 'Unlimited revisions',
        included: webFeatureList,
      },
    ],
  },
};

export const pricingCategoryIds = Object.keys(pricingCategories);
